language: php

php:
  - '8.1.2'
  - nightly

before_script:
  - sudo apt-get update -y
  - sudo apt-get upgrade -y
  - sudo apt install -y software-properties-common
  - sudo add-apt-repository -y ppa:ondrej/php
  - sudo apt-get update -y
  - sudo apt install -y unzip curl
  - sudo apt install -y php8.1 php8.1-common php8.1-sqlite3 php8.1-xml php8.1-xmlrpc php8.1-curl php8.1-cli php8.1-mbstring php8.1-bcmath php8.1-zip
  - composer install
  - sudo mv composer.phar /usr/local/bin/composer
  - cp .env_sample .env
  - composer install
  - ./phinx migrate
  - for P in src tests; do find $P -type f -name '*.php' -exec php -l {} \;; done

install:
  - export PATH="$HOME/.composer/vendor/bin:$PATH"