language: php
arch: amd64
dist: focal

php:
  - '8.1.2'
  - nightly

before_install:
  - sudo apt-get update -y
  - sudo apt-get install -y unzip curl libargon2-0 libargon2-1
  - sudo apt-get install -y php-sqlite3 php-xml php-xmlrpc php-curl php-cli php-mbstring php-bcmath php-zip
  - composer install
  - sudo mv composer.phar /usr/local/bin/composer
  - cp .env_sample .env

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
  - phinx migrate

script: phpunit

matrix:
  allow_failures:

addons:
  apt:
    update: true

install:
  - export PATH="$HOME/.composer/vendor/bin:$PATH"