language: php
arch: amd64
dist: focal

php:
  - '8.1.2'

before_install:
  - sudo apt-get update -y
  - sudo apt-get install -y unzip curl libargon2-0 libargon2-1
  - sudo apt-get install -y php8.1-sqlite3 php8.1-xml php8.1-xmlrpc php8.1-curl php8.1-cli php8.1-mbstring php8.1-bcmath php8.1-zip
  - sudo apt-cache search xmlrpc
  - sudo phpenv config-add php.travis.ini

before_script:
  - composer self-update
  - composer update
  - composer install --prefer-source --no-interaction --dev
  - cp .env_sample .env
  - phinx migrate

script: phpunit

addons:
  apt:
    update: true

install:
  - export PATH="$HOME/.composer/vendor/bin:$PATH"