#!/usr/bin/php
<?php declare(strict_types=1);

namespace Xeros;

include 'bootstrap.php';

// get address and port to use
$listenIp = Config::getListenAddress();
$listenPort = Config::getListenPort();

// if we have an address provided, use the command line value instead
if (!empty($argv[1])) {
    $listenIp = $argv[1];
}

// if we have a port provided, use the command line value instead
if (!empty($argv[2])) {
    $listenPort = (int)$argv[2];
}

// create the node and get online
$node = new Node();
$node->listen($listenIp, $listenPort);
